version: "4.17"
services:
  database:
    container_name: db_container
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_HOST=$MYSQL_HOST
    image: mysql:latest
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - backend
    
    
  
  server:
    container_name: server_container
    depends_on:
      - database
    build: ./server
    restart: "no"
    env_file: ./.env
    ports: 
      - '3001:3001'
    networks:
      - backend
      # - frontend
    command: npm run integration-test
    
    
  # client:
  #   container_name: client_container
  #   depends_on:
  #     - server
  #   image: 
  #   ports: 
  #     - '3000:3000'
  #   networks:
  #     - frontend
  #   stdin_open: true
  #   tty: true



networks:
  backend:
  # frontend: