GET http://localhost:3001/api/user/account?userID=6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjYsImlhdCI6MTY4NDkwMTM1OCwiZXhwIjoxNjg0OTAxMzY4fQ.YfLL_yQNKHvAqExM8yWXWIXLA0OMxvhn6nax3avVkPo
Content-Type: application/json