POST http://localhost:3001/api/user/refresh?userID=6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2IiwiaWF0IjoxNjg0OTAzNzUzLCJleHAiOjE2ODQ5MDM3NjN9.4wMtD9ttmY3s4g7KD1-YZF0JpqsNPcuQ1I9NmY7s8Kg
Content-Type: application/json