POST http://localhost:3001/api/game/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjI2NiwiaWF0IjoxNjg0NzMyNTgxLCJleHAiOjE2ODQ3MzI1OTF9.JlDFNv4kTolaXmzkBQsjidDE0lOFqX13uKFPs6ANLdM

{
  "data":{
  "userID": 266,
  "snippet_id": 424,
  "total_time": 20,
  "total_characters": 45,
  "wpm_data": [99, 10, 1],
  "wpm_avg": 10,
  "accuracy": 8,
  "num_mistakes": 500
  }
}